[GLOBAL]
pants_version = "2.9.0"
backend_packages.add = [
  "pants.backend.experimental.docker",
  "pants.backend.python"
]

[python]
interpreter_constraints = ["CPython==3.8.*"]

[source]
root_patterns = ["src/python"]
